name: COA Lookup Monitor

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (UTC)
  workflow_dispatch:        # Allow manual runs

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping COA Lookup with timeout and timing
        id: ping
        run: |
          echo "Pinging COA Lookup service..."
          START=$(date +%s)
          STATUS=$(curl -m 70 --connect-timeout 45 -s -w "%{http_code}" -o /dev/null https://coalookup-api.onrender.com/ping)
          END=$(date +%s)
          DURATION=$((END - START))
          echo "HTTP Status: $STATUS"
          echo "Ping duration: $DURATION seconds"
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          echo "duration=$DURATION" >> $GITHUB_OUTPUT

      - name: Send email if service is down
        if: steps.ping.outputs.status != '200'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🚨 COA Lookup DOWN"
          body: |
            The COA Lookup service at https://coalookup-api.onrender.com/ping is DOWN.
            Status code returned: ${{ steps.ping.outputs.status }}
            Ping duration: ${{ steps.ping.outputs.duration }} seconds
          to: stbcollc@gmail.com
          from: GitHub Monitor <${{ secrets.GMAIL_USER }}>
