name: COA Lookup Monitor

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:       # Allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping COA Lookup
        id: ping
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://coalookup-api.onrender.com/invalid-path)
          echo "HTTP Status: $STATUS"
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Send email if service is down
        if: steps.ping.outputs.status != '200'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "🚨 COA Lookup DOWN"
          body: |
            The COA Lookup service at https://coalookup-api.onrender.com/ping is DOWN.
            Status code returned: ${{ steps.ping.outputs.status }}
          to: stbcollc@gmail.com
          from: GitHub COA LU Monitor <${{ secrets.GMAIL_USER }}>
